<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:null="null" xmlns:p="http://www.w3.org/2001/XMLSchema"
	xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://www.iaas.uni-stuttgart.de" xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop"
	name="OrderingProcessSimple1" targetNamespace="http://www.iaas.uni-stuttgart.de"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">



	<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
		SERVICE DEFINITION - A service groups a set of ports into a service unit. 
		~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
	<plnk:partnerLinkType name="OrderingProcessSimple1PT">
		<plnk:role name="OrderProcessProvider" portType="tns:OrderingProcessSimple1" />
	</plnk:partnerLinkType>
	<plnk:partnerLinkType name="OrderingProcessSimple1CallbackPT">
		<plnk:role name="OrderProcessCallback" portType="tns:OrderingProcessSimple1Callback" />
	</plnk:partnerLinkType>

	<vprop:property name="correlProperty" type="xsd:string" />
	<vprop:propertyAlias propertyName="tns:correlProperty" messageType="tns:orderRequest" part="correlation"></vprop:propertyAlias>
	

	<types>
		<schema xmlns="http://www.w3.org/2001/XMLSchema"
			targetNamespace="http://www.iaas.uni-stuttgart.de"
			elementFormDefault="qualified">

		</schema>
	</types>
	<message name="orderRequest">
		<part name="acountNumber" type="xsd:string"/>
		<part name="status" type="xsd:string"/>
		<part name="orderTotalPrice" type="xsd:int"/>
		<part name="numDeliveries" type="xsd:int"/>
		<part name="correlation" type="xsd:string"/>
	</message>

	<portType name="OrderingProcessSimple1">
		<operation name="order">
			<input message="tns:orderRequest" name="order" />
		</operation>
	</portType>


	<binding name="OrderingProcessSimple1Binding" type="tns:OrderingProcessSimple1">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<operation name="order">
			<soap:operation soapAction="www.iaas.uni-stuttgart.de/order" />
			<input name="order">
				<soap:body use="literal" />
			</input>
		</operation>
	</binding>


	<service name="OrderingProcessSimple1">
		<port binding="tns:OrderingProcessSimple1Binding" name="OrderingProcessSimple1Port">
			<soap:address
				location="http://localhost:8080/ode/processes/OrderingProcessSimple1" />
		</port>
	</service>


</definitions>
